/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeusCalculosRouteImport } from './routes/meus-calculos'
import { Route as SimuladorRouteImport } from './routes/simulador'

const MeusCalculosRoute = MeusCalculosRouteImport.update({
  id: '/meus-calculos',
  path: '/meus-calculos',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/meus-calculos': typeof MeusCalculosRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRoutesByTo {
  '/meus-calculos': typeof MeusCalculosRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/meus-calculos': typeof MeusCalculosRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/meus-calculos' | '/simulador'
  fileRoutesByTo: FileRoutesByTo
  to: '/meus-calculos' | '/simulador'
  id: '__root__' | '/meus-calculos' | '/simulador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MeusCalculosRoute: typeof MeusCalculosRoute
  SimuladorRoute: typeof SimuladorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meus-calculos': {
      id: '/meus-calculos'
      path: '/meus-calculos'
      fullPath: '/meus-calculos'
      preLoaderRoute: typeof MeusCalculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MeusCalculosRoute: MeusCalculosRoute,
  SimuladorRoute: SimuladorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
