/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as AuthenticatedConfigAliquotasRouteImport } from './routes/_authenticated/config-aliquotas'
import { Route as AuthenticatedMeusCalculosRouteImport } from './routes/_authenticated/meus-calculos'
import { Route as AuthenticatedParametrosRouteImport } from './routes/_authenticated/parametros'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiPublicParecerPdfRouteImport } from './routes/api/public/parecer-pdf'
import { Route as ApiPublicRelatorioPdfRouteImport } from './routes/api/public/relatorio-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfigAliquotasRoute =
  AuthenticatedConfigAliquotasRouteImport.update({
    id: '/config-aliquotas',
    path: '/config-aliquotas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusCalculosRoute =
  AuthenticatedMeusCalculosRouteImport.update({
    id: '/meus-calculos',
    path: '/meus-calculos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametrosRoute = AuthenticatedParametrosRouteImport.update({
  id: '/parametros',
  path: '/parametros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicParecerPdfRoute = ApiPublicParecerPdfRouteImport.update({
  id: '/api/public/parecer-pdf',
  path: '/api/public/parecer-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRelatorioPdfRoute = ApiPublicRelatorioPdfRouteImport.update({
  id: '/api/public/relatorio-pdf',
  path: '/api/public/relatorio-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/simulador': typeof SimuladorRoute
  '/config-aliquotas': typeof AuthenticatedConfigAliquotasRoute
  '/meus-calculos': typeof AuthenticatedMeusCalculosRoute
  '/parametros': typeof AuthenticatedParametrosRoute
  '/s/$token': typeof STokenRoute
  '/api/public/parecer-pdf': typeof ApiPublicParecerPdfRoute
  '/api/public/relatorio-pdf': typeof ApiPublicRelatorioPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/simulador': typeof SimuladorRoute
  '/config-aliquotas': typeof AuthenticatedConfigAliquotasRoute
  '/meus-calculos': typeof AuthenticatedMeusCalculosRoute
  '/parametros': typeof AuthenticatedParametrosRoute
  '/s/$token': typeof STokenRoute
  '/api/public/parecer-pdf': typeof ApiPublicParecerPdfRoute
  '/api/public/relatorio-pdf': typeof ApiPublicRelatorioPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/simulador': typeof SimuladorRoute
  '/_authenticated/config-aliquotas': typeof AuthenticatedConfigAliquotasRoute
  '/_authenticated/meus-calculos': typeof AuthenticatedMeusCalculosRoute
  '/_authenticated/parametros': typeof AuthenticatedParametrosRoute
  '/s/$token': typeof STokenRoute
  '/api/public/parecer-pdf': typeof ApiPublicParecerPdfRoute
  '/api/public/relatorio-pdf': typeof ApiPublicRelatorioPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/simulador'
    | '/config-aliquotas'
    | '/meus-calculos'
    | '/parametros'
    | '/s/$token'
    | '/api/public/parecer-pdf'
    | '/api/public/relatorio-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/simulador'
    | '/config-aliquotas'
    | '/meus-calculos'
    | '/parametros'
    | '/s/$token'
    | '/api/public/parecer-pdf'
    | '/api/public/relatorio-pdf'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/simulador'
    | '/_authenticated/config-aliquotas'
    | '/_authenticated/meus-calculos'
    | '/_authenticated/parametros'
    | '/s/$token'
    | '/api/public/parecer-pdf'
    | '/api/public/relatorio-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SimuladorRoute: typeof SimuladorRoute
  STokenRoute: typeof STokenRoute
  ApiPublicParecerPdfRoute: typeof ApiPublicParecerPdfRoute
  ApiPublicRelatorioPdfRoute: typeof ApiPublicRelatorioPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/config-aliquotas': {
      id: '/_authenticated/config-aliquotas'
      path: '/config-aliquotas'
      fullPath: '/config-aliquotas'
      preLoaderRoute: typeof AuthenticatedConfigAliquotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-calculos': {
      id: '/_authenticated/meus-calculos'
      path: '/meus-calculos'
      fullPath: '/meus-calculos'
      preLoaderRoute: typeof AuthenticatedMeusCalculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametros': {
      id: '/_authenticated/parametros'
      path: '/parametros'
      fullPath: '/parametros'
      preLoaderRoute: typeof AuthenticatedParametrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/parecer-pdf': {
      id: '/api/public/parecer-pdf'
      path: '/api/public/parecer-pdf'
      fullPath: '/api/public/parecer-pdf'
      preLoaderRoute: typeof ApiPublicParecerPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/relatorio-pdf': {
      id: '/api/public/relatorio-pdf'
      path: '/api/public/relatorio-pdf'
      fullPath: '/api/public/relatorio-pdf'
      preLoaderRoute: typeof ApiPublicRelatorioPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfigAliquotasRoute: typeof AuthenticatedConfigAliquotasRoute
  AuthenticatedMeusCalculosRoute: typeof AuthenticatedMeusCalculosRoute
  AuthenticatedParametrosRoute: typeof AuthenticatedParametrosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfigAliquotasRoute: AuthenticatedConfigAliquotasRoute,
  AuthenticatedMeusCalculosRoute: AuthenticatedMeusCalculosRoute,
  AuthenticatedParametrosRoute: AuthenticatedParametrosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SimuladorRoute: SimuladorRoute,
  STokenRoute: STokenRoute,
  ApiPublicParecerPdfRoute: ApiPublicParecerPdfRoute,
  ApiPublicRelatorioPdfRoute: ApiPublicRelatorioPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
